export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CHANGE_TODOS_CATEGORY = 'CHANGE_TODOS_CATEGORY';
export const EDIT_TODO = 'EDIT_TODO';
export const TRIGGER_TODO_CHECK = 'TRIGGER_TODO_CHECK';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';
export const CHANGE_DISPLAYED_CATEGORY_ID = 'CHANGE_DISPLAYED_CATEGORY_ID';

export const TOGGLE_VISIBILITY_FILTER = 'TOGGLE_VISIBILITY_FILTER';
export const UPDATE_SEARCH_REQUEST = 'UPDATE_SEARCH_REQUEST';
export const RESET_SEARCH = 'RESET_SEARCH';
